### ISSUE TITLE
auth headless init is missing the following inputParams

### ISSUE THREAD

**Issue by dseeker** [ambientlight/amplify-cli-action#10]
I can't figure out what's wrong here or where to add the missing information.
Local deploys are working, but the GH action is failing
```
configure amplify
GraphQL endpoint: 
Run ambientlight/amplify-cli-action@0.2.1
/usr/bin/docker run --name [....] "src" "dist" "npm run build" "configure" "dev" "true" "" ""
using amplify available at PATH
/usr/local/bin/amplify
amplify version Scanning for plugins...
Plugin scan successful
4.18.1
found existing environment dev
- Fetching updates to backend environment: dev from the cloud.
✔ Successfully pulled backend environment dev from the cloud.
✖ There was an error pulling the backend environment dev.
auth headless init is missing the following inputParams facebookAppIdUserPool, facebookAppSecretUserPool, googleAppIdUserPool, googleAppSecretUserPool, loginwithamazonAppIdUserPool, loginwithamazonAppSecretUserPool
Error: auth headless init is missing the following inputParams facebookAppIdUserPool, facebookAppSecretUserPool, googleAppIdUserPool, googleAppSecretUserPool, loginwithamazonAppIdUserPool, loginwithamazonAppSecretUserPool
    at updateConfigOnEnvInit (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/provider-utils/awscloudformation/index.js:369:15)
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/index.js:234:28
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/promise-sequential/index.js:16:18
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by ambientlight** [comment]
@dseeker: sorry for missing your issue originally, do you still suffer from this problem?

**Comment by dseeker** [comment]
not anymore, I think the error message was misleading because I didn't add any extra info and it stopped.

**Comment by dseeker** [comment]
I've tried deploying a new environment from an existing project and the same problem occurred again. Puzzling..

**Comment by ambientlight** [comment]
@dseeker: not sure if this is an issue on `amplify_cli` side...
